version: 2

defaults_node: &defaults_node
  docker:
    - image: circleci/node:8-browsers
      environment:
        JOBS: 2

defaults_python: &defaults_python
  docker:
    - image: circleci/python
      environment:
        JOBS: 2

install_awscli: &install_awscli
  run:
    name: Install awscli
    command: pip install awscli

node_key: &node_key
  key: node-deps-v1-{{ arch }}-{{ checksum "yarn.lock" }}-{{ checksum "circle.yml" }}

restore_node: &restore_node
  restore_cache:
    <<: *node_key

save_bundle_to_workspace: &save_bundle_to_workspace
  persist_to_workspace:
    root: dist
    paths:
      - bundle.js.gz

attach_workspace_bundle: &attach_workspace_bundle
  attach_workspace:
    at: /tmp/dist/

jobs:
  build:
    <<: *defaults_node

    steps:
      - checkout

      - <<: *restore_node
      - run:
          name: Node dependencies
          command: |
            if [ ! -d node_modules ]; then
              yarn --pure-lockfile
            fi
      - save_cache:
          <<: *node_key
          paths:
            - node_modules
      - run:
          name: Build bundle
          command: npx webpack -p
      - <<: *save_bundle_to_workspace

  deploy_demo:
    <<: *defaults_python

    environment:
      ENV: demo

    steps:
      - checkout
      - <<: *install_awscli
      - <<: *attach_workspace_bundle

      - run:
          name: Deploy to demo
          command: aws s3 cp /tmp/dist/bundle.js.gz s3://${DEMO_AWS_BUCKET}/dfp-ad-templates/bundle.js --region ${DEMO_AWS_REGION} --acl public-read --cache-control max-age=0 --content-type "application/javascript" --content-encoding "gzip"

  deploy_production:
    <<: *defaults_python
    <<: *install_awscli

    environment:
      ENV: prod

    steps:
      - checkout
      - <<: *install_awscli
      - <<: *attach_workspace_bundle

      - run:
          name: Deploy to production
          command: aws s3 cp /tmp/dist/bundle.js.gz s3://${PROD_AWS_BUCKET}/dfp-ad-templates/bundle.js --region ${PROD_AWS_REGION} --acl public-read --cache-control max-age=0 --content-type "application/javascript" --content-encoding "gzip"



workflows:
  version: 2
  install-test-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy_production:
          requires:
            - build
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              ignore: /.*/
      - deploy_demo:
          requires:
            - build
          filters:
            branches:
              only: master
